CREATE TABLE IF NOT EXISTS workflow_definitions (
    id INTEGER PRIMARY KEY,
    workflow_name VARCHAR(255) NOT NULL,
    workflow_snapshot CLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS workflow_instances (
    id INTEGER PRIMARY KEY,
    workflow_id INTEGER NOT NULL,
    workflow_name VARCHAR(255) NOT NULL,
    current_task_id INTEGER NOT NULL,
    state VARCHAR(255) NOT NULL,
    retry_count INTEGER NOT NULL,
    last_failure_details VARCHAR(255) NOT NULL,
    workflow_snapshot CLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS workflow_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id INTEGER NOT NULL,
    sequence_no INTEGER NOT NULL,
    event_text VARCHAR(2000) NOT NULL
);
